package wasi:clocks@0.3.0-rc-2025-09-16;

@unstable(feature = clocks-timezone)
interface timezone {
    @unstable(feature = clocks-timezone)
    use system-clock.{instant};

    /// Return the IANA identifier of the currently configured timezone. The id
    /// `UTC` indicates Coordinated Universal Time. Otherwise, this should be an
    /// identifier from the IANA Time Zone Database.
    ///
    /// For displaying to a user, the identifier should be converted into a
    /// localized name by means of an internationalization API.
    ///
    /// In implementations that do not expose an actual time zone, this
    /// should be the string `UTC`.
    ///
    /// In time zones that do not have an applicable name, a formatted
    /// representation of the UTC offset may be returned, such as `-04:00`.
    @unstable(feature = clocks-timezone)
    id: func() -> string;

    /// The number of nanoseconds difference between UTC time and the local
    /// time of the currently configured timezone at the exact time of
    /// `instant`.
    ///
    /// The magnitude of the returned value will always be less than
    /// 86,400,000,000,000 which is the number of nanoseconds in a day
    /// (24*60*60*1e9).
    ///
    /// In implementations that do not expose an actual time zone, this
    /// should return 0.
    @unstable(feature = clocks-timezone)
    utc-offset: func(when: instant) -> s64;
}
